<?php
require 'bootstrap.php';

if($_GET['listObjects'] == true && $_GET['items'] == true && isset($_GET['prefix'])){
	$listObjects = $restConnection->listObjects(array("bucket"=>DEFAULT_BUCKET, "maxResults"=>"5000", "delimiter"=>"/", "prefix"=>$_GET['prefix']));
	$jsTreeObjects = convertGcsToJstree(array('listObjects'=>$listObjects));
	echo json_encode($jsTreeObjects);
  	exit;
}
if($_GET['listObjects'] == true && $_GET['items'] == true){
	$listObjects = $restConnection->listObjects(array("bucket"=>DEFAULT_BUCKET, "delimiter"=>"/"));
	echo json_encode(convertGcsToJstree(array('listObjects'=>$listObjects)));
  	exit;
}
if($_GET['getObject'] == true && isset($_GET['object'])){
	try{
	  $object = $restConnection->getObject(array("bucket"=>DEFAULT_BUCKET, "object"=>$_GET['object']));
	  echo json_encode($object);
	} catch (Google\Cloud\Exception\ServiceException $e){
		    echo $e->getMessage();
	}
  	exit;
}
if($_GET['downloadObject'] == true && isset($_GET['object'])){
	header("Content-Disposition: attachment; filename=".end(explode('/',$storage->bucket(DEFAULT_BUCKET)->object($_GET['object'])->name())));
	echo $storage->bucket(DEFAULT_BUCKET)->object($_GET['object'])->downloadAsStream();
  	exit;
}

/*	 
	JSTREE ITEM
	id          : "string" // will be autogenerated if omitted
	text        : "string" // node text
	icon        : "string" // string for custom
	state       : {
	opened    : boolean  // is the node open
	disabled  : boolean  // is the node disabled
	selected  : boolean  // is the node selected
	},
	children    : []  // array of strings or objects
	li_attr     : {}  // attributes for the generated LI node
	a_attr      : {}  // attributes for the generated A node
*/


function convertGcsToJstree($args){
	$listObjects = $args['listObjects'];
	$jsTreeObjects = array();
	$jsChildren = array();
	//Get prefixes if there are any
	if(isset($listObjects['prefixes'])){
		foreach($listObjects['prefixes'] as $prefix){
			$jsTreeObjects[] = array(
				'id'=>$prefix,
				'text'=>jsTreeDisplayName($prefix), 
				'children'=>true,
				'li_attr'=>array('gcs_id'=>$prefix)	
			);
		}
	}
	//Get objects
	if(isset($listObjects['items'])){
		foreach($listObjects['items'] as $object){
			$jsonObj = $object;
			$jsonObj['li_attr'] = array('gcs_id' => $object['name']);
			$jsonObj['text'] = jsTreeDisplayName($jsonObj['name']);
			$jsTreeObjects[] = $jsonObj;
		}
	}
	return $jsTreeObjects;
}

function jsTreeDisplayName($name) {
	$pieces = explode('/', $name);
	for($i=sizeof($pieces); $i>=0; $i--){
		if(strlen($pieces[$i]) > 0){
			return $pieces[$i];
		}		
	}
	return 'ERROR';
};

?>
